name: "RSpec"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: bundle install --with=ci

    - name: Run tests
      run: bundle exec rake spec_github

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'rspec.xml'
